// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUJwjbG90x6qOiL49qlmnSQaon4RU5TX8',
    appId: '1:237594317943:web:a9df203f837ea09653a272',
    messagingSenderId: '237594317943',
    projectId: 'food-delivery-app-users-fd60d',
    authDomain: 'food-delivery-app-users-fd60d.firebaseapp.com',
    storageBucket: 'food-delivery-app-users-fd60d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9xP2RuK9WiSbBKBZy7gSp8r9z7btUGZI',
    appId: '1:237594317943:android:a1f90d9cb0805ffd53a272',
    messagingSenderId: '237594317943',
    projectId: 'food-delivery-app-users-fd60d',
    storageBucket: 'food-delivery-app-users-fd60d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3mgrU4zKHQlulfPSzEOajLIARzILFdAw',
    appId: '1:237594317943:ios:027ad9612479a56253a272',
    messagingSenderId: '237594317943',
    projectId: 'food-delivery-app-users-fd60d',
    storageBucket: 'food-delivery-app-users-fd60d.appspot.com',
    iosClientId: '237594317943-9aqk6pth8bibqv8tj3hu3c3o3o7ea6s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3mgrU4zKHQlulfPSzEOajLIARzILFdAw',
    appId: '1:237594317943:ios:027ad9612479a56253a272',
    messagingSenderId: '237594317943',
    projectId: 'food-delivery-app-users-fd60d',
    storageBucket: 'food-delivery-app-users-fd60d.appspot.com',
    iosClientId: '237594317943-9aqk6pth8bibqv8tj3hu3c3o3o7ea6s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
